# Generated by Django 5.0 on 2024-02-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('appinment_time', models.CharField(max_length=20)),
                ('appoinment_for_reason', models.CharField(max_length=100)),
                ('otp_number', models.CharField(max_length=20)),
            ],
        ),
    ]
