# Generated by Django 5.0 on 2024-02-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_table',
            old_name='appoinment_for_reason',
            new_name='appoinment_time',
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='appinment_time',
        ),
        migrations.AddField(
            model_name='register_table',
            name='reason_for_appointment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
