# Generated by Django 5.0 on 2024-02-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_rename_appoinment_for_reason_register_table_appoinment_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_table',
            old_name='appoinment_time',
            new_name='appointment_time',
        ),
    ]
