# Generated by Django 5.0 on 2024-02-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_rename_appoinment_time_register_table_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_table',
            old_name='reason_for_appointment',
            new_name='reason_for_the_appointment',
        ),
    ]
